version: "3.4"

services:
  go-demo-app:
    build: .
    ports:
      - 8081:80
    volumes:
      - ~/.scope:/root/.scope
    environment:
      - CI
      - SCOPE_DSN
      - CIRCLECI
      - CIRCLE_BUILD_NUM
      - CIRCLE_BUILD_URL
      - JENKINS_URL
      - BUILD_ID
      - BUILD_NUMBER
      - BUILD_URL
      - GIT_COMMIT=$GIT_COMMIT
      - APP_IMAGES_SVC=https://csharp-demo-app.undefinedlabs.dev/
      - APP_RESTAURANT_SVC=https://java-demo-app.undefinedlabs.dev/
      - APP_RATING_SVC=https://python-demo-app.undefinedlabs.dev/
