version: "3.4"

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=restaurant_ratings
      - POSTGRES_USER=restUser
      - POSTGRES_PASSWORD=restPassw0rd
